/**
 * Data constants
 * Lists for dropdowns and selections
 */

export const BANKS = [
  'Banco do Brasil',
  'Bradesco',
  'Caixa Econômica Federal',
  'Itaú Unibanco',
  'Santander',
  'Nubank',
  'Inter',
  'C6 Bank',
  'BTG Pactual',
  'Banco Original',
  'Banco Pan',
  'Banco Safra',
  'Banrisul',
  'Sicoob',
  'Sicredi',
  'Banco do Nordeste',
  'Neon',
  'Next',
  'PagBank',
  'Mercado Pago',
  'Picpay',
  'Outros',
].sort();

export const CARD_BRANDS = [
  'Visa',
  'Mastercard',
  'Elo',
  'American Express',
  'Hipercard',
  'Diners Club',
  'Discover',
  'JCB',
  'Aura',
].sort();

export const ACCOUNT_TYPES = [
  'Conta Corrente',
  'Conta Poupança',
  'Conta Investimento',
  'Conta Salário',
  'Conta Digital',
];

export const CATEGORIES = {
  expense: [
    '🍽️ Alimentação',
    '🚗 Transporte',
    '🏠 Moradia',
    '⚡ Contas',
    '🎓 Educação',
    '💊 Saúde',
    '🎮 Lazer',
    '👕 Vestuário',
    '💇 Beleza',
    '🐕 Pet',
    '🎁 Presentes',
    '📱 Telefone/Internet',
    '💳 Taxas Bancárias',
    '🛒 Compras',
    '✈️ Viagens',
    '🔧 Manutenção',
    '📚 Assinaturas',
    '💰 Investimentos',
    '🎯 Outros',
  ],
  income: [
    '💼 Salário',
    '💰 Freelance',
    '📈 Investimentos',
    '🎁 Presente',
    '🏆 Bônus',
    '💵 Reembolso',
    '🏠 Aluguel',
    '🔄 Transferência',
    '🎯 Outros',
  ],
};

export const PAYMENT_METHODS = [
  { id: 'cash', label: '💵 Dinheiro', needsAccount: false },
  { id: 'pix', label: '📱 PIX', needsAccount: true },
  { id: 'debit', label: '💳 Cartão de Débito', needsAccount: true },
  { id: 'credit', label: '💳 Cartão de Crédito', needsAccount: true },
  { id: 'boleto', label: '📄 Boleto', needsAccount: false },
  { id: 'transfer', label: '🔄 Transferência', needsAccount: true },
  { id: 'other', label: '🎯 Outros', needsAccount: false },
];

export const EXPENSE_TYPES = [
  { id: 'variable', label: 'Variável' },
  { id: 'fixed', label: 'Fixo' },
];

export const TRANSACTION_TYPES = [
  { id: 'expense', label: 'Despesa', color: '#ef4444' },
  { id: 'income', label: 'Receita', color: '#10b981' },
];

export const SUBSCRIPTION_SERVICES = [
  'Netflix',
  'Amazon Prime Video',
  'Spotify',
  'YouTube Premium',
  'Disney+',
  'HBO Max',
  'Apple Music',
  'Deezer',
  'Globoplay',
  'Paramount+',
  'Star+',
  'Crunchyroll',
  'Academia SmartFit',
  'Academia Bluefit',
  'Academia Bio Ritmo',
  'iFood',
  'Uber One',
  'PlayStation Plus',
  'Xbox Game Pass',
  'Nintendo Switch Online',
  'Adobe Creative Cloud',
  'Microsoft 365',
  'Google One',
  'iCloud+',
  'Dropbox',
  'Outros',
].sort();

export const GOAL_TYPES = [
  { id: 'individual', label: 'Individual' },
  { id: 'shared', label: 'Compartilhada' },
];

export const WISH_CATEGORIES = [
  'Lazer',
  'Compras',
  'Livre',
];

export const GOAL_ICONS = [
  { name: 'flight-takeoff', label: 'Viagem' },
  { name: 'home', label: 'Casa' },
  { name: 'directions-car', label: 'Carro' },
  { name: 'school', label: 'Educação' },
  { name: 'favorite', label: 'Casamento' },
  { name: 'child-care', label: 'Filho' },
  { name: 'business-center', label: 'Negócio' },
  { name: 'savings', label: 'Poupança' },
  { name: 'beach-access', label: 'Férias' },
  { name: 'phone-iphone', label: 'Eletrônico' },
  { name: 'computer', label: 'Computador' },
  { name: 'watch', label: 'Relógio' },
  { name: 'diamond', label: 'Joia' },
  { name: 'sports-esports', label: 'Games' },
  { name: 'fitness-center', label: 'Saúde' },
  { name: 'pets', label: 'Pet' },
];

export const WISH_ICONS = [
  { name: 'phone-iphone', label: 'Celular' },
  { name: 'computer', label: 'Notebook' },
  { name: 'headphones', label: 'Fone' },
  { name: 'watch', label: 'Relógio' },
  { name: 'tv', label: 'TV' },
  { name: 'speaker', label: 'Caixa Som' },
  { name: 'camera-alt', label: 'Câmera' },
  { name: 'sports-esports', label: 'Console' },
  { name: 'checkroom', label: 'Roupa' },
  { name: 'shopping-bag', label: 'Bolsa' },
  { name: 'restaurant', label: 'Restaurante' },
  { name: 'local-cafe', label: 'Café' },
  { name: 'movie', label: 'Cinema' },
  { name: 'theater-comedy', label: 'Show' },
  { name: 'attractions', label: 'Parque' },
  { name: 'book', label: 'Livro' },
];

export const WISH_OPTIONS = [
  { icon: 'flight-takeoff', label: 'Viagem' },
  { icon: 'restaurant', label: 'Jantar' },
  { icon: 'local-activity', label: 'Passeio' },
  { icon: 'movie', label: 'Cinema' },
  { icon: 'theater-comedy', label: 'Show' },
  { icon: 'card-giftcard', label: 'Presente' },
  { icon: 'spa', label: 'Spa' },
  { icon: 'sports-soccer', label: 'Evento Esportivo' },
  { icon: 'local-mall', label: 'Shopping' },
  { icon: 'phone-iphone', label: 'Eletrônico' },
  { icon: 'checkroom', label: 'Roupa' },
  { icon: 'watch', label: 'Acessório' },
  { icon: 'celebration', label: 'Festa' },
  { icon: 'cake', label: 'Comemoração' },
  { icon: 'attractions', label: 'Parque' },
  { icon: 'beach-access', label: 'Praia' },
  { icon: 'hiking', label: 'Aventura' },
  { icon: 'music-note', label: 'Concerto' },
  { icon: 'book', label: 'Curso/Livro' },
  { icon: 'more-horiz', label: 'Outros' },
];

// Achievements System
export interface Achievement {
  id: string;
  title: string;
  description: string;
  emoji: string;
  xp: number;
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  category: 'registro' | 'metas' | 'colaboracao' | 'contas' | 'habitos';
}

export const ACHIEVEMENTS: Achievement[] = [
  // Categoria: Registro Constante
  {
    id: 'b1',
    title: 'Registro Constante',
    description: 'Registre 5 transações no total',
    emoji: '📝',
    xp: 20,
    rarity: 'common',
    category: 'registro',
  },
  {
    id: 'b2',
    title: 'Mãos à Obra',
    description: 'Registre uma transação por 7 dias consecutivos',
    emoji: '✍️',
    xp: 20,
    rarity: 'common',
    category: 'registro',
  },
  {
    id: 'b3',
    title: 'Controle Total',
    description: 'Registre 50 transações',
    emoji: '📊',
    xp: 35,
    rarity: 'uncommon',
    category: 'registro',
  },
  {
    id: 'b5',
    title: 'Guardiões do Mês',
    description: 'Feche um mês com pelo menos uma transação em cada categoria principal',
    emoji: '🗓️',
    xp: 40,
    rarity: 'uncommon',
    category: 'registro',
  },
  {
    id: 'b6',
    title: 'Sem Mistérios',
    description: 'Classifique manualmente 10 transações que vieram sem categoria',
    emoji: '🔍',
    xp: 15,
    rarity: 'common',
    category: 'registro',
  },
  {
    id: 'b7',
    title: 'Dupla Enxuta',
    description: 'Finalize o mês gastando menos do que o orçamento definido',
    emoji: '💪',
    xp: 90,
    rarity: 'rare',
    category: 'registro',
  },
  {
    id: 'b8',
    title: 'XP na Mão',
    description: 'Registre 10 receitas (rendimentos) diferentes',
    emoji: '💰',
    xp: 30,
    rarity: 'uncommon',
    category: 'registro',
  },
  {
    id: 'b9',
    title: '100% Categorizado',
    description: 'Termine um mês sem nenhuma transação na categoria "Outras Despesas"',
    emoji: '✅',
    xp: 150,
    rarity: 'epic',
    category: 'registro',
  },
  {
    id: 'b10',
    title: 'Dupla Analítica',
    description: 'Visualize o relatório mensal na página "Relatórios" por 3 meses seguidos',
    emoji: '📈',
    xp: 35,
    rarity: 'uncommon',
    category: 'registro',
  },
  // Categoria: Metas
  {
    id: 'b11',
    title: 'A Rota do Ouro',
    description: 'Crie 3 metas de economia diferentes',
    emoji: '🗺️',
    xp: 20,
    rarity: 'common',
    category: 'metas',
  },
  {
    id: 'b12',
    title: 'Tijolo por Tijolo',
    description: 'Contribua 5 vezes para a mesma meta',
    emoji: '🧱',
    xp: 25,
    rarity: 'uncommon',
    category: 'metas',
  },
  {
    id: 'b13',
    title: 'Elevador da Fortuna',
    description: 'Complete 1 meta de economia',
    emoji: '🎯',
    xp: 80,
    rarity: 'rare',
    category: 'metas',
  },
  {
    id: 'b14',
    title: 'Casal Visionário',
    description: 'Tenha pelo menos uma meta partilhada ativa com o(a) parceiro(a)',
    emoji: '👥',
    xp: 35,
    rarity: 'uncommon',
    category: 'metas',
  },
  {
    id: 'b15',
    title: 'Crescimento Contínuo',
    description: 'Mantenha contribuições semanais a uma meta por 1 mês',
    emoji: '📅',
    xp: 15,
    rarity: 'common',
    category: 'metas',
  },
  {
    id: 'b16',
    title: 'Tesouro Duplo',
    description: 'Ambos os parceiros contribuem para a mesma meta partilhada',
    emoji: '💎',
    xp: 100,
    rarity: 'rare',
    category: 'metas',
  },
  {
    id: 'b17',
    title: 'Guardiões dos Sonhos',
    description: 'Complete 3 metas no total',
    emoji: '🏆',
    xp: 150,
    rarity: 'epic',
    category: 'metas',
  },
  {
    id: 'b18',
    title: 'Estratégia Firme',
    description: 'Edite o valor alvo ou o prazo de uma meta existente',
    emoji: '🎲',
    xp: 30,
    rarity: 'uncommon',
    category: 'metas',
  },
  {
    id: 'b19',
    title: 'Mirando Alto',
    description: 'Crie uma meta com valor alvo superior a R$ 10.000',
    emoji: '🚀',
    xp: 120,
    rarity: 'rare',
    category: 'metas',
  },
  {
    id: 'b20',
    title: 'O Cofre Secreto',
    description: 'Complete uma meta com valor alvo acima de R$ 20.000',
    emoji: '🔐',
    xp: 250,
    rarity: 'legendary',
    category: 'metas',
  },
  // Categoria: Colaboração
  {
    id: 'b21',
    title: 'Comunicação é Tudo',
    description: 'Envie a primeira notificação personalizada para o(a) parceiro(a)',
    emoji: '💬',
    xp: 10,
    rarity: 'common',
    category: 'colaboracao',
  },
  {
    id: 'b22',
    title: 'Alinhamento Perfeito',
    description: 'Ambos atualizam os "Nossos Acordos" financeiros no mesmo mês',
    emoji: '🤝',
    xp: 20,
    rarity: 'common',
    category: 'colaboracao',
  },
  {
    id: 'b23',
    title: 'Feedback Duo',
    description: 'Ambos avaliam o mês na "Jornada Duo"',
    emoji: '📝',
    xp: 35,
    rarity: 'uncommon',
    category: 'colaboracao',
  },
  {
    id: 'b24',
    title: 'Conversas Sábias',
    description: 'Responda a 5 perguntas da "Jornada Duo"',
    emoji: '🧠',
    xp: 40,
    rarity: 'uncommon',
    category: 'colaboracao',
  },
  {
    id: 'b25',
    title: 'Missão Conjunta',
    description: 'Ambos completam uma meta partilhada',
    emoji: '🎊',
    xp: 80,
    rarity: 'rare',
    category: 'colaboracao',
  },
  {
    id: 'b26',
    title: 'Parceiros Disciplinados',
    description: 'Feche 3 meses seguidos dentro do orçamento definido',
    emoji: '🎖️',
    xp: 75,
    rarity: 'rare',
    category: 'colaboracao',
  },
  {
    id: 'b27',
    title: 'Vibração Positiva',
    description: 'Envie um elogio financeiro para o(a) parceiro(a) através do app',
    emoji: '⭐',
    xp: 15,
    rarity: 'common',
    category: 'colaboracao',
  },
  {
    id: 'b28',
    title: 'Conexão Diária',
    description: 'Ambos entram no app por 14 dias consecutivos',
    emoji: '🔗',
    xp: 35,
    rarity: 'uncommon',
    category: 'colaboracao',
  },
  {
    id: 'b29',
    title: 'Duo Imbatível',
    description: 'Ambos atingem todas as suas metas individuais e partilhadas no mesmo mês',
    emoji: '👑',
    xp: 150,
    rarity: 'epic',
    category: 'colaboracao',
  },
  {
    id: 'b30',
    title: 'Lendas Financeiras',
    description: 'Colabore por 6 meses consecutivos, atingindo as metas de poupança conjuntas',
    emoji: '🌟',
    xp: 500,
    rarity: 'legendary',
    category: 'colaboracao',
  },
  // Categoria: Contas e Cartões
  {
    id: 'b31',
    title: 'O Cartão Misterioso',
    description: 'Cadastre 2 cartões de crédito',
    emoji: '💳',
    xp: 15,
    rarity: 'common',
    category: 'contas',
  },
  {
    id: 'b32',
    title: 'Mapa das Contas',
    description: 'Adicione 3 contas bancárias',
    emoji: '🗺️',
    xp: 20,
    rarity: 'common',
    category: 'contas',
  },
  {
    id: 'b33',
    title: 'Vida Organizada',
    description: 'Atualize o limite ou a data de vencimento de um cartão',
    emoji: '📋',
    xp: 30,
    rarity: 'uncommon',
    category: 'contas',
  },
  {
    id: 'b34',
    title: 'Raio-X Financeiro',
    description: 'Adicione saldo inicial em 5 contas ou cartões diferentes',
    emoji: '🔬',
    xp: 40,
    rarity: 'uncommon',
    category: 'contas',
  },
  {
    id: 'b35',
    title: 'Sem Surpresas',
    description: 'Consulte o relatório de fatura por 3 meses',
    emoji: '📊',
    xp: 15,
    rarity: 'common',
    category: 'contas',
  },
  {
    id: 'b36',
    title: 'Caçador de Taxas',
    description: 'Pague a fatura de um cartão de crédito em dia por 3 meses seguidos',
    emoji: '🎯',
    xp: 90,
    rarity: 'rare',
    category: 'contas',
  },
  {
    id: 'b37',
    title: 'Controle é Poder',
    description: 'Edite as informações de uma conta ou cartão',
    emoji: '⚙️',
    xp: 35,
    rarity: 'uncommon',
    category: 'contas',
  },
  {
    id: 'b38',
    title: 'Zero Dívidas',
    description: 'Zere o saldo devedor de todas as faturas e contas no final do mês',
    emoji: '🎉',
    xp: 200,
    rarity: 'epic',
    category: 'contas',
  },
  {
    id: 'b39',
    title: 'Carteira Premium',
    description: 'Cadastre 5 cartões de crédito',
    emoji: '👛',
    xp: 120,
    rarity: 'rare',
    category: 'contas',
  },
  {
    id: 'b40',
    title: 'Tudo Sob Controle',
    description: 'Pague todas as faturas do mês em dia e contribua para todas as metas ativas',
    emoji: '🏅',
    xp: 300,
    rarity: 'legendary',
    category: 'contas',
  },
  // Categoria: Hábitos
  {
    id: 'b41',
    title: 'Primeira Semana Brilhante',
    description: 'Complete 7 dias de uso da aplicação',
    emoji: '✨',
    xp: 10,
    rarity: 'common',
    category: 'habitos',
  },
  {
    id: 'b42',
    title: 'A Rotina é Rainha',
    description: 'Complete 30 dias de uso contínuo',
    emoji: '👸',
    xp: 30,
    rarity: 'uncommon',
    category: 'habitos',
  },
  {
    id: 'b43',
    title: 'Foco Total',
    description: 'Passe 7 dias consecutivos sem registar uma transação marcada como "compra por impulso"',
    emoji: '🧘',
    xp: 75,
    rarity: 'rare',
    category: 'habitos',
  },
  {
    id: 'b44',
    title: 'Duo Desafiado',
    description: 'Participe de um desafio mensal proposto pela aplicação',
    emoji: '🎮',
    xp: 30,
    rarity: 'uncommon',
    category: 'habitos',
  },
  {
    id: 'b45',
    title: 'Meta Secreta',
    description: 'Crie e complete uma meta pessoal marcada como "oculta"',
    emoji: '🕵️',
    xp: 150,
    rarity: 'epic',
    category: 'habitos',
  },
  {
    id: 'b46',
    title: 'Modo Ninja',
    description: 'Revise as finanças no app antes das 8h da manhã por 5 dias seguidos',
    emoji: '🥷',
    xp: 15,
    rarity: 'common',
    category: 'habitos',
  },
  {
    id: 'b47',
    title: 'Radar Financeiro',
    description: 'Abra a aplicação todos os dias durante um mês',
    emoji: '📡',
    xp: 30,
    rarity: 'uncommon',
    category: 'habitos',
  },
  {
    id: 'b48',
    title: 'Mês Perfeito',
    description: 'Feche um mês sem nenhuma despesa atrasada e sem transações por categorizar',
    emoji: '💯',
    xp: 180,
    rarity: 'epic',
    category: 'habitos',
  },
  {
    id: 'b49',
    title: 'Guardião dos Dados',
    description: 'Exporte o seu primeiro relatório em PDF',
    emoji: '📄',
    xp: 90,
    rarity: 'rare',
    category: 'habitos',
  },
  {
    id: 'b50',
    title: 'Lenda da Prosperidade',
    description: 'Por 3 meses consecutivos, atinja as metas de poupança, fique dentro do orçamento e pague todas as faturas em dia',
    emoji: '🏛️',
    xp: 400,
    rarity: 'legendary',
    category: 'habitos',
  },
];

export const RARITY_COLORS = {
  common: '#9ca3af',
  uncommon: '#3b82f6',
  rare: '#8b5cf6',
  epic: '#ec4899',
  legendary: '#f59e0b',
};
